### ISSUE TITLE
it is not compatible with guzzle >=6 

### ISSUE THREAD

**Issue by yuseferi** [kamermans/guzzle-oauth2-subscriber#22]
Hi,

I'm using guzzle 6.4 on my project but after using your package I face with 

> PHP Fatal error:  Interface 'GuzzleHttp\Event\SubscriberInterface' not found in /srv/www/application/vendor/kamermans/guzzle-oauth2-subscriber/src/OAuth2Subscriber.php on line 15

after some investigation on the guzzle package github, I noticed this interface has been renamed.

**Comment by alexeyshockov** [comment]
Could you provide more info, like you add the OAuth middleware to your Guzzle client? A reproducible example would be great.

**Comment by namelivia** [comment]
I can confirm this for Guzzle 7.
For example [here](https://github.com/kamermans/guzzle-oauth2-subscriber/blob/master/src/Utils/Helper.php#L12) the code is accessing to `GuzzleHttp\ClientInterface::VERSION` which is not present on Guzzle7 anymore.
I have a Dependabot PR upgrading Guzzle from 6 to 7 that [raises a bunch of errors like that one](https://travis-ci.com/github/namelivia/fitbit-http-php/jobs/355177547) on TravisCI.
I will try to take a look at this if I have some spare time this month and fix the compatibility issues.

**Comment by lasselehtinen** [comment]
I am facing the same issue, I have created a [PR for this](https://github.com/kamermans/guzzle-oauth2-subscriber/pull/25).

**Comment by kamermans** [comment]
Hi all, sorry for the delayed response, I'll merge the PR from @lasselehtinen to resolve this.

**Comment by kamermans** [comment]
@yuseferi your error is caused by using the `OAuth2Subscriber` with Guzzle 6, but it only works for Guzzle 5 and below.  For Guzzle 6+ you should use the `OAuth2Middleware` as described here: https://github.com/kamermans/guzzle-oauth2-subscriber#middleware-guzzle-6
