### ISSUE TITLE
It seems not possible to forward custom Guzzle options to the handler

### ISSUE THREAD

**Issue by RoNoLo** [kamermans/guzzle-oauth2-subscriber#24]
In guzzle it is possible to add cURL options via the $options and the ['curl'] key. I happens to have to deal with a expired SSL cert by a companies sandbox uri. I *think* I could just move forward, when I add the curl Option to ignore the ssl verify.

This option is ignored in the getAccessToken() process from this middleware. I tracked it down to the ClientCredentials.php:70 where the send($request) is done without an $options array. I think there should be something to forward curl options down the callstack.

**Comment by kamermans** [comment]
Hi @RoNoLo, sorry about the slow delay!  You can set `'verify' => false` on the Guzzle client itself so all requests are unverified:

```php
// Authorization client - this is used to request OAuth access tokens
$reauth_client = new GuzzleHttp\Client([
    // Disable SSL verification
    'verify' => false,
]);
$reauth_config = [
    // ...
];
$grant_type = new ClientCredentials($reauth_client, $reauth_config);
$oauth = new OAuth2Subscriber($grant_type);
```
