### ISSUE TITLE
Please update v1.0.2 zip files to include latest change.

### ISSUE THREAD

**Issue by mitrpaka** [kamermans/guzzle-oauth2-subscriber#3]
It seems that v1.0.2 zip files are the very same as for v1.0.1 release. At least "Fix RefreshToken" update is missing from zip files.

Now with composer update project version is updated to v1.0.2 in the lock file, but zip file downloaded doesn't include changes introduced in v1.0.2

Error: Call to undefined method kamermans\OAuth2\GrantType\RefreshToken::getTokenData() in kamermans\OAuth2\OAuth2Handler->requestNewAccessToken() (line 222 of xxx/kamermans/guzzle-oauth2-subscriber/src/OAuth2Handler.php)

**Comment by mitrpaka** [comment]
Hmm ... and now looking this more carefully it looks like that release was created July 21 but does not include latest two changes done that day.

Would you mind doing other minor release or should I switch to dev for time being..

**Comment by kamermans** [comment]
Sorry about the delay, I just got back from nginx.conf in Portland.  I'll make another release for 1.0.3 right now.

**Comment by kamermans** [comment]
Here's the new release, and thanks for reporting!
https://github.com/kamermans/guzzle-oauth2-subscriber/releases/tag/v1.0.3
