### ISSUE TITLE
Provide an example for using refresh token grant type with other grants

### ISSUE THREAD

**Issue by rjmackay** [kamermans/guzzle-oauth2-subscriber#5]
Could you provide an example using ClientCreds grant together with refresh token grant?

**Comment by azrulamir** [comment]
Yes, I would like to know that also very much.

**Comment by alithedeveloper** [comment]
Please do provide an example on mentioned work flow

**Comment by kamermans** [comment]
Hi all, the RFC states that the Client Credentials grant type cannot be used with Refresh Tokens: https://tools.ietf.org/html/rfc6749#section-4.4.3

That said, I see no reason why it cannot work technically, and if you can please provide me with some examples of sites that are doing this, I can come up with a workflow for you.  For example, if you tell me that Rackspace (or whatever other company) uses this method, I will try it out on my account.

Thanks!

**Comment by kamermans** [comment]
Hi all, I have created a comprehensive example of using refresh tokens with other grant types, despite it being discouraged by the RFC.  Please take a look here: https://github.com/kamermans/guzzle-oauth2-subscriber/issues/9#issuecomment-381457409

Here's the TL;DR version of using `ClientCredentials` with `RefreshToken`:
```php
// This grant type is used to get a new Access Token and Refresh Token when 
//  no valid Access Token or Refresh Token is available
$grant_type = new ClientCredentials($reauth_client, $reauth_config);

// This grant type is used to get a new Access Token and Refresh Token when
//  only a valid Refresh Token is available
$refresh_grant_type = new RefreshToken($reauth_client, $reauth_config);

// Tell the middleware to use the two grant types
$oauth = new OAuth2Middleware($grant_type, $refresh_grant_type);
```
