### ISSUE TITLE
incompatible with guzzlehttp/guzzle 7.7.0 along with guzzlehttp/promises 2.0.0

### ISSUE THREAD

**Issue by kaczenski** [kamermans/guzzle-oauth2-subscriber#52]
Please be aware that the current version `1.0.12`  does not work with `guzzlehttp/promises` in version `2.0.0`, which can be installed along with `guzzlehttp/guzzle` in version `7.7.0`. Anyhow, version `7.7.0` still allows `guzzlehttp/promises` in version `1.5.3`.

e.g. calling to undefined method `rejection_for` in `\kamermans\OAuth2\OAuth2Middleware::onRejected`
 
    private function onRejected(RequestInterface $request, array $options, $handler)
    {
        return function ($reason) use ($request, $options) {
            return \GuzzleHttp\Promise\rejection_for($reason);
        };
    }

**Comment by kamermans** [comment]
Thanks for the bug report @kaczenski, I'll try to get this fixed.

**Comment by elburro1887** [comment]
I also ran into this today. Seems like the "Function API" was removed in Promises 2.0.0
See: https://github.com/guzzle/promises#upgrading-from-function-api

**Comment by kamermans** [comment]
Thanks for the confirmation and the migration link, I'll see if I can get a test branch up today.

**Comment by kamermans** [comment]
I've got a PR up with support for Guzzle Promises 2.0.0:
https://github.com/kamermans/guzzle-oauth2-subscriber/pull/53

**Comment by kamermans** [comment]
Note that the status checks in my PR are using Guzzle 7.7.0 with Promises 2.2.0 and they are passing 🤞 
https://github.com/kamermans/guzzle-oauth2-subscriber/actions/runs/5513376738/jobs/10051432683?pr=53

**Comment by elburro1887** [comment]
just tested it with my app, it works! thanks for the quick fix!
