### ISSUE TITLE
PHP 8.1 show user deprecated warnings on return types

### ISSUE THREAD

**Issue by evs-xsarus** [kamermans/guzzle-oauth2-subscriber#55]
Could these be fixed in a new release:

> 2023-08-10T16:30:21+02:00 [info] User Deprecated: Method "IteratorAggregate::getIterator()" might add "\Traversable" as a native return type declaration in the future. Do the same in implementation "kamermans\OAuth2\Utils\Collection" now to avoid errors or add an explicit @return annotation to suppress this message.
> 2023-08-10T16:30:21+02:00 [info] User Deprecated: Method "ArrayAccess::offsetGet()" might add "mixed" as a native return type declaration in the future. Do the same in implementation "kamermans\OAuth2\Utils\Collection" now to avoid errors or add an explicit @return annotation to suppress this message.
> 2023-08-10T16:30:21+02:00 [info] User Deprecated: Method "ArrayAccess::offsetSet()" might add "void" as a native return type declaration in the future. Do the same in implementation "kamermans\OAuth2\Utils\Collection" now to avoid errors or add an explicit @return annotation to suppress this message.
> 2023-08-10T16:30:21+02:00 [info] User Deprecated: Method "ArrayAccess::offsetExists()" might add "bool" as a native return type declaration in the future. Do the same in implementation "kamermans\OAuth2\Utils\Collection" now to avoid errors or add an explicit @return annotation to suppress this message.
> 2023-08-10T16:30:21+02:00 [info] User Deprecated: Method "ArrayAccess::offsetUnset()" might add "void" as a native return type declaration in the future. Do the same in implementation "kamermans\OAuth2\Utils\Collection" now to avoid errors or add an explicit @return annotation to suppress this message.
> 2023-08-10T16:30:21+02:00 [info] User Deprecated: Method "Countable::count()" might add "int" as a native return type declaration in the future. Do the same in implementation "kamermans\OAuth2\Utils\Collection" now to avoid errors or add an explicit @return annotation to suppress this message.

**Comment by kamermans** [comment]
Sure, I'll try to get these fixed before the next release unless someone puts in a PR first :)

**Comment by coudenysj** [comment]
@kamermans The PR is there, would you be able to check and tag it? 🙏🏼

**Comment by kamermans** [comment]
@coudenysj could you try PR #60?  I'm planning to bump the min version to 7.1 or 7.2 in that PR.

**Comment by kamermans** [comment]
Great, I've released it at `v1.1.0` :)
