### ISSUE TITLE
How to manually set an access token?

### ISSUE THREAD

**Issue by ammonkc** [kamermans/guzzle-oauth2-subscriber#6]
There doesn't seem to be a grant_type for setting the access token manually. I'm a little unclear how to manually set the access type. A simple little example would be appreciated. Thanks

**Comment by kamermans** [comment]
Hi @ammonkc, sorry about the slow response!  You're correct, there is no `grant_type` for setting the token manually, although you can set it via `OAuth2Middleware::setAccessToken()` or `OAuth2Subscriber::setAccessToken()` (it's inherited from `OAuth2Handler::setAccessToken()`).  For example, if you are using Guzzle 6, you could do this:

```php
// Mock reauth client since it's required for instantiation
$reauth_client = new Client(['base_uri' => 'http://localhost']);
$reauth_config = [
    "client_id" => "none",
    "client_secret" => "none"
];
$grant_type = new ClientCredentials($reauth_client, $reauth_config);
$oauth = new OAuth2Middleware($grant_type);

// Set access token manually
$oauth->setAccessToken([
    'access_token' => 'abcdefghijklmnop',
]);
```

**Comment by kamermans** [comment]
I was kind of annoyed that the only way to handle this is to mock a grant type that you don't want to use, so I added a new `NullGrantType` adapter to make it a little more clean, and I've documented the process for using a manual access token: https://github.com/kamermans/guzzle-oauth2-subscriber#manually-setting-an-access-token

**Comment by arderyp** [comment]
@kamermans I know this is old but figured it was better to ask here rather than open a new issue

I am using your new NullGrantType following the exact documentation but getting "No access token is present and there is no way to obtain one with NullGrantType", but I am indeed passing `['access_token' => 'abcdefg']`  into `setAccessToken()`

Any thoughts?

**Comment by arderyp** [comment]
Nevermind, I think the issue was with a stale/invalid token.  may be helpful for the system to throw a more meaningful error if the token is bad versus not being present.
