### ISSUE TITLE
RFC: flexible field naming

### ISSUE THREAD

**Issue by pbowyer** [kamermans/guzzle-oauth2-subscriber#8]
Thanks for this library, it's been really easy to integrate with!

I've used it to authenticate with Salesforce Marketing Cloud's REST API. The only complication was that the field names returned by the authentication endpoint are different from those `guzzle-oauth2-subscriber` expects (`accessToken` vs `access_token`, `expiresIn` vs `expires_in`) so I had to subclass `ClientCredentials` to modify the returned data:
```
<?php

namespace IACircularEmails\SFMC;

use kamermans\OAuth2\GrantType\ClientCredentials;
use kamermans\OAuth2\Signer\ClientCredentials\SignerInterface;

class SFMCClientCredentials extends ClientCredentials
{
    public function getRawData(SignerInterface $clientCredentialsSigner, $refreshToken = null)
    {
        $data = parent::getRawData($clientCredentialsSigner, $refreshToken);

        $data['access_token'] = $data['accessToken'];
        unset($data['accessToken']);
        $data['expires_in'] = $data['expiresIn'];
        unset($data['expiresIn']);

        return $data;
    }
}
```

The request field names can be configured when setting up the middleware, without any need for subclassing:
```
$oauth = new OAuth2Middleware(
                              $grant_type, 
                              null, 
                              new PostFormData('clientId', 'clientSecret'), 
                              new QueryString()
                             );
```

Would you consider adding mapping to the `ClientCredentials` class, as [HWIOAuthBundle does with paths](https://github.com/hwi/HWIOAuthBundle/blob/master/Resources/doc/internals/response_object_and_paths.md)? An example is:
```
$reauth_config = [
    "client_id" => "xxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "client_secret" => "******************************",
    "mappings" => [
        "access_token" => 'accessToken',
        "expires_in" => 'expiresIn',
    ]
];
$grant_type = new ClientCredentials($reauth_client, $reauth_config);
```

**Comment by kamermans** [comment]
Hi @pbowyer, thanks for the suggestion, I think it's a great idea.  Are you able to add the field name mapping support and send a PR?

**Comment by pbowyer** [comment]
Thanks for the feedback @kamermans. Yes I'll get a PR created in the next couple of weeks.

**Comment by kamermans** [comment]
@pbowyer what do you think about trying to guess the field name, so `access_token` and `accessToken` are both matched?  This could be done, for example, by removing all characters except letters and numbers, then doing a case-insensitive match against `accesstoken`.
